Repository rinikerlab/PyGromosTools, pull requests merged in 2021-12, with the labels that each got.

#108 Seperating ana from traj
  examples/example_PyGromosPP.ipynb
  examples/example_TI_gromos_simulation.ipynb
  examples/example_gromos_files.ipynb
  examples/example_gromos_simulation.ipynb
  pygromos/files/trajectory/tre.py
Labels: enhancement

#136 hotfixes Tre
  pygromos/files/trajectory/tre.py
Labels: bug, Done

#140 Hvap fix
  pygromos/analysis/energy_analysis.py
  pygromos/files/trajectory/tre.py
Labels: bug
