Repository rinikerlab/PyGromosTools, pull requests merged in 2022-03, with the labels that each got.

#234 XYZ bug fix
  pygromos/files/coord/cnf.py
Labels: bug

#229 Mtb
  pygromos/files/blocks/_all_blocks.py
  pygromos/files/blocks/mtb_blocks.py
  pygromos/files/blocks/topology_blocks.py
  pygromos/files/topology/mtb.py
  pygromos/tests/test_files/test_mtb.py
Labels: feature

#235 Removing-unnecessary-ClassVariables
  pygromos/files/__init__.py
  pygromos/files/_basics/_general_gromos_file.py
  pygromos/files/blocks/__init__.py
  pygromos/files/blocks/_all_blocks.py
  pygromos/files/blocks/_general_blocks.py
  pygromos/files/blocks/energy_blocks.py
  pygromos/files/coord/posres.py
  pygromos/files/coord/refpos.py
  pygromos/files/otherfiles/noe_output.py
  pygromos/files/otherfiles/residue_library.py
  pygromos/files/qmmm/qmmm.py
Labels: Done, cleaning

#228 GromosBinaryDetectionChangedLocation
  dev/conda_envs/test_env.yaml
  pygromos/_version.py
  pygromos/files/gromos_system/gromos_system.py
  pygromos/gromos/_gromosClass.py
  pygromos/gromos/gromosPP.py
  pygromos/gromos/gromosXX.py
  pygromos/tests/test_gromos/test_gromosPP.py
  pygromos/tests/test_gromos/test_gromosXX.py
  pygromos/utils/compiledProgram.py
Labels: enhancement, in progress

#241 ff rework
  examples/example_amber2gromos.ipynb
  examples/example_hvap.ipynb
  pygromos/files/forcefield/__init__.py
  pygromos/files/forcefield/_generic_force_field.py
  pygromos/files/forcefield/amber/__init__.py
  pygromos/files/forcefield/amber/amberff.py
  pygromos/files/forcefield/gromos/__init__.py
  pygromos/files/forcefield/gromos/gromosff.py
  pygromos/files/forcefield/openff/__init__.py
  pygromos/files/forcefield/openff/openff.py
  pygromos/files/forcefield/serenityff/__init__.py
  pygromos/files/forcefield/serenityff/serenityff.py
  pygromos/files/forcefield/serenityff/serenityff_data/.gitignore
  pygromos/files/forcefield/serenityff/serenityff_data/__init__.py
  pygromos/files/gromos_system/ff/forcefield_system.py
  pygromos/files/gromos_system/ff/solvents/Solvents.py
  pygromos/files/gromos_system/ff/solvents/_base.py
  pygromos/files/gromos_system/gromos_system.py
  pygromos/files/topology/ifp.py
  pygromos/files/topology/mtb.py
  pygromos/simulations/approaches/hvap_calculation/hvap_calculation.py
  pygromos/simulations/approaches/solvation_free_energy_calculation/solvation_free_energy.py
  pygromos/tests/test_approaches/test_solvation_free_ernergy.py
  pygromos/tests/test_files/test_gromosSystem_forcefields.py
Labels: feature, in progress, cleaning

#244 Small changes and bug fixes to solvation free energy approach
  examples/example_solvation_free_energy.ipynb
  pygromos/simulations/approaches/solvation_free_energy_calculation/solvation_free_energy.py
  pygromos/tests/test_approaches/test_solvation_free_ernergy.py
Labels: Done, cleaning

#240 Gromos modules
  .gitignore
  .gitmodules
  dev/build_pygromosfully.py
  dev/conda_envs/dev_env_withGromos.yaml
  pygromos/gromos/__init__.py
  pygromos/gromos/compile_gromos.py
  pygromos/utils/utils.py
Labels: feature, in progress
