Repository rinikerlab/PyGromosTools, pull requests merged in 2022-02, with the labels that each got.

#175 str2bool for dynamic_parser
  pygromos/utils/utils.py
Labels: bug

#207 Reinit-Fix
  pygromos/simulations/hpc_queuing/job_scheduling/workers/simulation_workers/simulation_run_worker.py
Labels: bug, in progress

#209 Addresses issue #208
  pygromos/files/gromos_system/gromos_system.py
  pygromos/simulations/hpc_queuing/job_scheduling/schedulers/scheduler_functions.py
  pygromos/utils/bash.py
Labels: bug

#210 update_reinitialization for simulations
  pygromos/simulations/hpc_queuing/job_scheduling/schedulers/scheduler_functions.py
  pygromos/simulations/hpc_queuing/job_scheduling/schedulers/simulation_scheduler.py
  pygromos/simulations/hpc_queuing/job_scheduling/workers/simulation_workers/simulation_run_worker.py
  pygromos/simulations/modules/general_simulation_modules.py
  pygromos/simulations/modules/preset_simulation_modules.py
Labels: bug, enhancement

#176 PyGromosToolsDay
  .github/workflows/CI.yaml
  examples/PyGromosToolsDay/figures/PyGromos_Issues.png
  examples/PyGromosToolsDay/figures/gromos_file.png
  examples/PyGromosToolsDay/figures/gromos_system_overview.png
  examples/PyGromosToolsDay/figures/job_scheduler.png
  examples/PyGromosToolsDay/figures/simulation_structure.png
  examples/PyGromosToolsDay/pyGromosToolsDay.ipynb
  pygromos/data/simulation_parameters_templates/vac_emin.imd
  pygromos/data/simulation_parameters_templates/vacuum_sd.imd
  pygromos/files/blocks/_all_blocks.py
  pygromos/files/blocks/mtb_blocks.py
  pygromos/files/coord/cnf.py
  pygromos/files/gromos_system/gromos_system.py
  pygromos/files/topology/mtb.py
  pygromos/simulations/approaches/solvation_free_energy_calculation/solvation_free_energy.py
  pygromos/simulations/hpc_queuing/job_scheduling/schedulers/scheduler_functions.py
Labels: documentation, enhancement, in progress

#204 Trajectory update tre
  examples/example_files/Traj_files/test_CHE_H2O_bilayer.tre.h5
  examples/example_files/Traj_files/test_CHE_vacuum_sd.trc.h5
  examples/example_gromos_trajectories.ipynb
  pygromos/files/coord/cnf.py
  pygromos/files/trajectory/_general_trajectory.py
  pygromos/files/trajectory/blocks/trajectory_blocks.py
  pygromos/files/trajectory/trc.py
  pygromos/files/trajectory/tre.py
  pygromos/files/trajectory/tre_field_libs/ene_fields.py
Labels: enhancement, Done

#218 CI update
  .github/workflows/CI.yaml
Labels: enhancement

#217 Test warnings
  pygromos/simulations/modules/preset_simulation_modules.py
  pygromos/simulations/modules/ti_modules.py
  pygromos/tests/test_simulation_blocks/test_simulation_runner_blocks.py
  pygromos/tests/test_submission/test_hpc_queuing_submission_scheduling.py
  pygromos/tests/test_submission/test_hpc_queuing_submission_systems.py
Labels: enhancement

#214 Added tests for bash functions
  pygromos/tests/test_utils/test_bash.py
Labels: enhancement

#230 integrating ambertools pipeline
  examples/example_amber2gromos.ipynb
  examples/example_files/amber2gromos/aniline.mol2
  pygromos/data/topology_templates/spc.top
  pygromos/files/gromos_system/ff/amber2gromos.py
  pygromos/files/gromos_system/ff/forcefield_system.py
  pygromos/files/gromos_system/gromos_system.py
  pygromos/gromos/gromosPP.py
Labels: feature
