Repository rinikerlab/PyGromosTools, pull requests merged in 2022-01, with the labels that each got.

#151 fixed assymetric c6 assignment
  pygromos/files/gromos_system/ff/serenityff/serenityff.py
Labels: bug, Done

#154 Qmmm functionality and more gromos++ wrapper functions
  examples/example_files/QMMM_files/md.imd
  examples/example_files/QMMM_files/menthol-methanol-dmf.qmmm
  examples/example_gromos_qmmm.ipynb
  examples/example_submission_systems.ipynb
  pygromos/files/blocks/_all_blocks.py
  pygromos/files/blocks/imd_blocks.py
  pygromos/files/blocks/qmmm_blocks.py
  pygromos/files/qmmm/__init__.py
  pygromos/files/qmmm/qmmm.py
  pygromos/files/simulation_parameters/imd.py
  pygromos/gromos/gromosPP.py
  pygromos/simulations/modules/general_simulation_modules.py
  pygromos/tests/in_testfiles/qmmm/md.imd
  pygromos/tests/in_testfiles/qmmm/menthol-methanol-dmf.qmmm
  pygromos/tests/test_files/test_qmmm.py
Labels: enhancement, feature, in progress

#164 documentation top
  pygromos/files/topology/top.py
Labels: documentation, Done

#145 Rework sub sys2
  .gitignore
  examples/example_files/submission-system-files/menthol-dmf-example-all-atom_54a7.cnf
  examples/example_files/submission-system-files/menthol-dmf-example-all-atom_54a7.top
  examples/example_gromos_new_submission_system.ipynb
  examples/example_gromos_simulation.ipynb
  examples/tutorial_gromos_pipeline.ipynb
  pygromos/files/_basics/_general_gromos_file.py
  pygromos/files/coord/cnf.py
  pygromos/files/gromos_system/ff/serenityff/serenityff.py
  pygromos/files/gromos_system/gromos_system.py
  pygromos/simulations/approaches/hvap_calculation/hvap_input_files/liquid_eq.imd
  pygromos/simulations/approaches/hvap_calculation/hvap_input_files/liquid_md.imd
  pygromos/simulations/hpc_queuing/job_scheduling/schedulers/scheduler_functions.py
  pygromos/simulations/hpc_queuing/job_scheduling/schedulers/simulation_scheduler.py
  pygromos/simulations/hpc_queuing/job_scheduling/workers/analysis_workers/simulation_analysis.py
  pygromos/simulations/hpc_queuing/job_scheduling/workers/simulation_workers/clean_up_simulation_files.py
  pygromos/simulations/hpc_queuing/job_scheduling/workers/simulation_workers/simulation_run_worker.py
  pygromos/simulations/hpc_queuing/submission_systems/_submission_system.py
  pygromos/simulations/hpc_queuing/submission_systems/dummy.py
  pygromos/simulations/hpc_queuing/submission_systems/local.py
  pygromos/simulations/hpc_queuing/submission_systems/lsf.py
  pygromos/simulations/hpc_queuing/submission_systems/submission_job.py
  pygromos/simulations/modules/general_simulation_modules.py
  pygromos/tests/test_submission/test_hpc_queuing_submission_job.py
  pygromos/tests/test_submission/test_hpc_queuing_submission_systems.py
Labels: enhancement
